config/routes.rb
Incbot::Application.routes.draw do
  get 'pages/home'
  get 'pages/selection'
	root :to => 'pages#home'
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  resources :corporations 
  resources :pages

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/agent.rb
class Agent < ActiveRecord::Base
  attr_accessible :city, :country, :line1, :line2, :line3, :name, :postcode, :state
end

app/models/corporation.rb
class Corporation < ActiveRecord::Base

  belongs_to :user
  
  attr_accessible :filing_date, 
        				  :name, 
        				  :par_value, 
        				  :shares,
        				  :incorporator_name,
        				  :incorporator_street,
        				  :incorporator_zip,
        				  :incorporator_city,
        				  :incorporator_state,
        				  :incorporator_country,
                  :user_id

  attr_writer :current_step

  validates_presence_of :name, :if => :name?
  validates_presence_of :par_value, :if => :shares?
  validates_presence_of :shares, :if => :shares?

  def name?
    current_step == "name"
  end


  def shares?
    current_step == "shares"
  end

  def current_step
    @current_step || steps.first
  end

  def steps
    %w[name shares incorporator date]
  end

  def next_step
    self.current_step = steps[steps.index(current_step)+1]
  end

  def previous_step
    self.current_step = steps[steps.index(current_step)-1]
  end

  def first_step?
    current_step == steps.first
  end

  def last_step?
    current_step == steps.last
  end

  def all_valid?
    steps.all? do |step|
      self.current_step = step
      valid?
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  has_many :corporations

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/corporations_controller.rb
class CorporationsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  # GET /corporations
  # GET /corporations.json
  def index
    unless user_signed_in?
      @corporations = Corporation.all
    else
      @user = current_user
      @corporations = @user.corporations
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @corporations }
    end
  end

  # GET /corporations/1
  # GET /corporations/1.json
  def show
    @corporation = Corporation.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @corporation }
      format.pdf do
        pdf = CertificatePdf.new(@corporation)
        send_data pdf.render, type: "application/pdf", 
                              disposition: "inline"

      end
    end
  end

  # GET /corporations/new
  # GET /corporations/new.json
  def new
    session[:corporation_params] ||= {}
    @corporation = Corporation.new(session[:corporation_params])
    @corporation.current_step = session[:corporation_step]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @corporation }
    end
  end

  # GET /corporations/1/edit
  def edit
    @corporation = Corporation.find(params[:id])
  end

  # POST /corporations
  # POST /corporations.json
  def create
    session[:corporation_params].deep_merge!(params[:corporation]) if params[:corporation]
    @corporation = Corporation.new(session[:corporation_params])
    @corporation.current_step = session[:corporation_step]
    if @corporation.valid?
      if params[:back_button]
        @corporation.previous_step
      
      elsif @corporation.last_step?
        @corporation.save
      
      else
        @corporation.next_step         
      end

      session[:corporation_step] = @corporation.current_step
      end   
    if @corporation.new_record?
      render 'new'     

    else
      session[:corporation_step] = session[:corporation_params] = nil
      redirect_to @corporation
    end
  end

  # PUT /corporations/1
  # PUT /corporations/1.json
  def update
    @corporation = Corporation.find(params[:id])

    respond_to do |format|
      if @corporation.update_attributes(params[:corporation])
        format.html { redirect_to @corporation, notice: 'Corporation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @corporation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corporations/1
  # DELETE /corporations/1.json
  def destroy
    @corporation = Corporation.find(params[:id])
    @corporation.destroy

    respond_to do |format|
      format.html { redirect_to corporations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	def home
	end
	
	def selection
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corporations_helper.rb
module CorporationsHelper
end

app/views/corporations/_date_step.html.haml
.row
  .span12
    %h3 Step 4 - Options
    %h4 A. Filing date
    %strong When will the company be incorporated?
    %p You can choose to incorporate today or on a date in the future. 
    %br
    = f.input :filing_date, input_html: { width: 20 }, :label => false
    %br
    %h4 B. More options coming soon!   
    %p Incbot is in beta and will be improved over time.
    %br
    = f.button :submit, "Continue", class: "btn btn-primary btn-large"
    = f.button :submit, "Back", class: "btn btn-large btn-padding", :name => "back_button" unless @corporation.first_step?
    

app/views/corporations/_form.html.haml
= simple_form_for(@corporation) do |f|
  = f.error_notification

  %h5 1. Company name
  %br
  = f.input :name, label: "Enter the name of the new corporation"
  %br
  %h5 2. Authorized shares
  %br
  = f.input :shares, input_html: { :value => '10,000,000' }, label: "How many shares will the corporation have?"
  %br
  = f.input :par_value, input_html: { :value => '0.000001' }, label: "What will be the par value of these shares?"
  %br
  %h5 3. Incorporator
  %br
  = f.input :incorporator_name, label: "Who is the person incorporating this company?", placeholder: "Incorporator name"
  = f.input :incorporator_street, label: false, placeholder: "Street and housenumber"
  = f.input :incorporator_zip, label: false, placeholder: "Zip code"
  = f.input :incorporator_city, label: false, placeholder: "City"
  = f.input :incorporator_state, label: false, placeholder: "State"
  = f.input :incorporator_country, label: false, :priority => [ "United States" ]
  %br
  %h5 4. Incorporation date
  %br
  = f.input :filing_date, start_year: Date.today.year, label: "What will be the date of incorporation?", :input_html => {:style => 'width: 115px'}
  %br
  %br
  = f.button :submit, "Generate Documents", class: "btn btn-primary btn-large"
  -# The incorporation date should be set as a result of the completion of the filing.

app/views/corporations/_incorporator_step.html.haml
.row
  .span12
    %h3 Step 3 - Incorporator info
    %strong Who is the incorporator?
    %p This is the individual who signs the articles of incorporation and by doing so requests the state to bring the corporation into existence. The incorporator must be at least 18 years old.
    %br
    = f.input :incorporator_name, :label => false, placeholder: "Name"
    = f.input :incorporator_street, label: false, placeholder: "Address"
    = f.input :incorporator_zip, label: false, placeholder: "Zip code"
    = f.input :incorporator_city, label: false, placeholder: "City"
    = f.input :incorporator_state, label: false, placeholder: "State"
    = f.input :incorporator_country, label: false, :priority => [ "United States" ]
    %br
    = f.button :submit, "Continue", class: "btn btn-primary btn-large"
    = f.button :submit, "Go back", class: "btn btn-large btn-padding", :name => "back_button" unless @corporation.first_step?

app/views/corporations/_name_step.html.haml
.row
  .span12
    %h3 Step 1 - Choose a name
    %strong What is the name of this new corporation?
    %p The Delaware Secretary of State requires a unique company name. Stay clear of names protected by trademark or other rights.
    %br
    = f.input :name, :label => false, :wrappers => :append, :class => "inline" do
      = f.input_field :name
      %strong , Inc.

    = f.hidden_field :user_id, :value => current_user.id
    %br
    = f.button :submit, "Continue", class: "btn btn-primary btn-large"
    = f.button :submit, "Back", class: "btn btn-large", :name => "back_button" unless @corporation.first_step?

app/views/corporations/_shares_step.html.haml
.row
  .span12
    %h3 Step 2 - Stock preferences
    %h4 Authorized shares
    %strong How many shares can #{@corporation.name}, Inc. issue? 
    %p The number of authorized shares determines the maximum number of shares of stock that a company can issue. This can be amended with the necessary approvals.
    %br
    = f.input :shares, :label => false
    %br
    %h4 Par value
    %strong What is the value of these shares?
    %p The par value is the nominal value of the authorized shares as determined by the issuing company to be its minimum price. This choice has tax consequences.
    %br
    = f.input :par_value, :label => false
    %br
    %br
    = f.button :submit, "Continue", class: "btn-primary btn-large"
    = f.button :submit, "Go back", class: "btn-large btn-padding", :name => "back_button" unless @corporation.first_step?

app/views/corporations/_signup.html.haml
.row.home
  .span12
    %h1
      incbot new "incbot" -inc
    %h4.grey
      currently c-corp

app/views/corporations/_welcome.html.haml
.row.home
  .span5.well
    .row
      .span5
        %h2 Online Incorporation
        %br/
      .span1
        %br/
        %i.icon-file-alt.icon-4x
      .span4
        %h3 1. Prepare
        %p Generate legal forms using IncBot
    %br/
    .row
      .span1
        %br/
        %i.icon-search.icon-4x
      .span4
        %h3 2. Review
        %p Ask a lawyer to review before filing
    %br/
    .row
      .span1
        %br/
        %i.icon-signin.icon-4x
      .span4
        %h3 3. File
        %p Complete the filing from your desk
    %br/
    %br/

    = link_to 'Create a Delaware Corporation', new_corporation_path, :class => "btn btn-primary btn-large"

app/views/corporations/edit.html.haml
%h1 Editing corporation
= render 'new'
= link_to 'Show', @corporation
|
\#{link_to 'Back', corporations_path}

app/views/corporations/index.html.haml
- unless user_signed_in?
  = render 'welcome'

- else
  %h3 Your companies
  %br
  .row
    .span2
      %strong Name
    .span2
      %strong Shares
    .span2
      %strong Incorporator
    .span2
      %strong Filed

  %hr

  - @corporations.each do |corporation|
    .row
      .span2
        %p= corporation.name
      .span2
        %P= corporation.shares
      .span2
        %P= corporation.incorporator_name
      .span2
        %P= corporation.filing_date
      .span1.offset2
        %P= link_to 'View', corporation, :class => "btn btn-small"
      .span1
        %P= link_to 'Delete', corporation, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-small btn-danger"
    %hr
  %br/
  
  %h3 Recently incorporated componies

app/views/corporations/new.html.haml
= simple_form_for(@corporation) do |f|
  = f.error_notification
  = render "#{@corporation.current_step}_step", :f => f
-# The incorporation date should be set as a result of the completion of the filing.

app/views/corporations/show.html.haml
.row
  .span12
    %h3 Step 5 - Review and file
    %strong Your Certificate of Incorporation has been created. 
    %p Please review the certificate below before completing the e-filing. You will have the option to request an attorney review.
.row
  .span12
    .well
  
      %h4.center STATE of DELAWARE
      %h4.center CERTIFICATE of INCORPORATION
      %h4.center 
        = @corporation.name

      %br

      %p
        1. The name of the corporation shall be 
        %strong
          #{@corporation.name}, Inc.
      %p
        2. Its registered office in the State of Delaware is located at 1521 Concord Pike STE 303, In the city of Wilmington, DE 19803 and its Registered Agent at such address is A Registered Agent, Inc.
      %p
        3. The purpose of the corporation shall be to carry on any and all business and to engage in any lawful act or activity for which corporations may be organized under the General Corporation Law of Delaware.
      %p
        4. The total number of shares of stock which this corporation is authorized to issue is 
        %strong
          = @corporation.shares
        with a par value of
        %strong
          $
          = @corporation.par_value
        per share.
      %p
        5. The powers, preferences and rights and the qualifications, limitations or restrictions thereof shall be determined by the board of directors.

      %p
        6. The name and address of the incorporator is #{@corporation.incorporator_name}, located at #{@corporation.incorporator_street}, #{@corporation.incorporator_zip}, #{@corporation.incorporator_city}, #{@corporation.incorporator_state}, #{@corporation.incorporator_country}.

      %p
        7. The Board of Directors shall have the power to adopt, amend or repeal by by-laws.
      %p 
        8. No director shall be personally liable to the Corporation or its stockholders for monetary damages for any breach of fiduciary duty by such director as a director. Notwithstanding the foregoing sentence, a director shall be liable to the extent provided by applicable law, (i) for breach of the director's duty of loyalty to the Corporation or its stockholders, (ii) for acts or omissions not in good faith or which involve intentional misconduct or a knowing violation of law, (iii) pursuant to Section 174 of the Delaware General Corporation Law or (iv) for any transaction from which the director derived an improper personal benefit. No amendment to or repeal of this Article Eighth shall apply to or have any effect on the liability or alleged liability of any director of the Corporation for or with respect to any acts or omissions of such director occurring prior to such amendment.
      %p
        IN WITNESS WHEREOF, the undersigned, being the incorporator herein before named, has executed signed and acknowledged this certificate of incorporation on 
        = @corporation.filing_date.strftime("%B")
        = @corporation.filing_date.strftime("%d")
        of the year #{@corporation.filing_date.strftime("%Y")}.
.well
  %p
    = link_to 'Complete e-filing', '#', :class => "btn btn-primary btn-large center"
    %p        
    = link_to 'Download documents as pdf', corporation_path(@corporation, format: "pdf")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Incbot
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      .navbar-inner
        .container
          .logo
            = link_to image_tag("incbot.png", size: "25x25"), root_path, id: "logo"
          .logotext
            Incbot
          - if user_signed_in?
            = link_to '+ New Incorporation', new_corporation_path, :class => "btn btn-success"
          %ul.nav.pull-right
            - if user_signed_in?
              %li= link_to 'Edit profile', edit_user_registration_path
              %li
                \#{link_to "Logout", destroy_user_session_path, method: :delete}
            - else
              %li= link_to "Sign up", new_user_registration_path
              %li
                \#{link_to "Login", new_user_session_path}
    .container
      - if flash.alert
        .alert-container
          .alert.alert-error.fade.in{:'data-alert' => "alert"}
            = flash.alert
            %button.close{data: {dismiss: 'alert'}} ×
      - if flash.notice
        .alert-container
          .alert.alert-success.fade.in{:'data-alert' => "alert"}
            = flash.notice
            %button.close{data: {dismiss: 'alert'}} ×
      = yield

app/views/pages/home.html.haml
%br
%br
.row
  .span12.center
    %h1.jumbotron IncBot
    %h1 Incorporate and dissolve corporate entities online
    %br/
    %br/
    = link_to 'Incorporate now', {:controller => :pages, :action => :selection}, :class => 'btn btn-warning btn-xlarge'
    %br
    %br
    %br
    %p Incbot is in beta and currently only supports Delaware Corporations.
    %br
    %br
    %br
  .span12
    %hr 
    %h3.center.grey Incorporate in three easy steps
    %br
    %br
    %br
    .row
      .span4.center
        = image_tag 'illustrations/clipboard.png', :width => "120px"
        %h1 Prepare
        %p Generate legal forms using IncBot
      .span4.center
        = image_tag 'illustrations/retina.png', :width => "140px"
        %h1 Review
        %p Ask a lawyer to review your filing
      .span4.center
        = image_tag 'illustrations/mail.png', :width => "130px"
        %h1 File
        %p Complete the filing with a click
    

app/views/pages/selection.html.haml
%br
%br
%h3 I want to incorporate in Delaware, United States of America. Help me create a:
%br
%br
.row
  .span3
    %a{:href => new_corporation_path, :class => "nolines"}
      .entitySelect
        %h4.entitytext.big C Corporation
        .entitytext.subtitle
          %p Features
        .entitytext.small
          %p Liability protection
          %p Can have multiple stock classes
          %p Unlimited number of owners
          %p Entity subject to income tax
        .price $299 state fees
  
  .span3.entitySelect
    = link_to "", {:controller => "corporations", :action => "create"}
    %h4.entitytext.big S Corporation
    .entitytext.subtitle
      %p Features
    .entitytext.small
      %p Liability protection
      %p Can only have one stock class
      %p Maximum of 100 owners
      %p Owners subject to income tax
    .construction Not available yet
  .span3.entitySelect
    = link_to "", {:controller => "corporations", :action => "create"}
    %h4.entitytext.big LLC
    .entitytext.subtitle
      %p Features
    .entitytext.small
      %p Liability protection
      %p Can have multiple membership classes
      %p Unlimited number of owners
      %p Owners subject to income tax
    .construction Not available yet